export type QuizQuestion = {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
};

export const QUESTION_BANK: Record<string, QuizQuestion[]> = {
  "Operating System": [
    { question: "Which CPU scheduling algorithm gives the minimum average waiting time?", options: ["FCFS", "Round Robin", "SJF (Shortest Job First)", "Priority Scheduling"], correctAnswer: 2, explanation: "SJF minimizes average waiting time by always selecting the process with the smallest burst time next." },
    { question: "What is a deadlock in an operating system?", options: ["A process running infinitely", "A set of processes blocking each other waiting for resources", "High CPU usage causing slowdowns", "Memory overflow condition"], correctAnswer: 1, explanation: "Deadlock occurs when two or more processes are blocked, each waiting for resources held by the other." },
    { question: "Which of the following is NOT a condition for deadlock?", options: ["Mutual Exclusion", "Hold and Wait", "Preemption", "Circular Wait"], correctAnswer: 2, explanation: "The four conditions are: Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait. Preemption (allowing it) actually prevents deadlock." },
    { question: "What is a semaphore used for in OS?", options: ["Memory management", "Process synchronization", "CPU scheduling", "File management"], correctAnswer: 1, explanation: "Semaphores are used for process synchronization to control access to shared resources and prevent race conditions." },
    { question: "In demand paging, what happens when a page is not found in memory?", options: ["Process is killed", "Page fault occurs and the page is loaded from disk", "CPU is halted", "A new process is created"], correctAnswer: 1, explanation: "A page fault interrupt occurs, and the OS loads the required page from secondary storage into RAM." },
    { question: "Which memory allocation strategy avoids external fragmentation?", options: ["Paging", "Segmentation", "Variable partitioning", "Fixed partitioning"], correctAnswer: 0, explanation: "Paging divides memory into fixed-size frames, eliminating external fragmentation though internal fragmentation may occur." },
    { question: "What is thrashing in OS?", options: ["A virus attack on memory", "Excessive paging activity causing low CPU utilization", "CPU overheating", "Disk fragmentation"], correctAnswer: 1, explanation: "Thrashing happens when the OS spends more time swapping pages in/out than executing processes, causing performance collapse." },
    { question: "Which of these is a non-preemptive scheduling algorithm?", options: ["Round Robin", "SRTF", "FCFS", "Priority with preemption"], correctAnswer: 2, explanation: "FCFS (First Come First Served) is non-preemptive — a process runs until it finishes or blocks." },
    { question: "Belady's anomaly is associated with which page replacement algorithm?", options: ["LRU", "Optimal", "FIFO", "MFU"], correctAnswer: 2, explanation: "FIFO (First In First Out) page replacement can paradoxically increase page faults when more frames are added — this is Belady's anomaly." },
    { question: "What does IPC stand for in OS?", options: ["Internal Process Controller", "Inter-Process Communication", "Integrated Program Control", "Interrupt Process Command"], correctAnswer: 1, explanation: "IPC (Inter-Process Communication) allows processes to communicate and synchronize using pipes, message queues, shared memory, and sockets." },
    { question: "The dining philosophers problem illustrates:", options: ["CPU scheduling issues", "Memory leaks", "Deadlock and synchronization challenges", "File system corruption"], correctAnswer: 2, explanation: "The dining philosophers problem is a classic synchronization problem illustrating challenges of deadlock avoidance and resource sharing." },
    { question: "Which system call is used to create a new process in Unix/Linux?", options: ["exec()", "spawn()", "fork()", "create()"], correctAnswer: 2, explanation: "fork() creates a new process (child) as an exact copy of the calling (parent) process in Unix/Linux." },
  ],

  "Java Programming": [
    { question: "Which keyword is used to inherit a class in Java?", options: ["implements", "inherits", "extends", "super"], correctAnswer: 2, explanation: "The 'extends' keyword is used for class inheritance in Java. 'implements' is used for interfaces." },
    { question: "What is the output of: System.out.println(10/3);", options: ["3.33", "3", "4", "Compilation Error"], correctAnswer: 1, explanation: "Integer division in Java truncates the decimal part. 10/3 = 3 (integer result)." },
    { question: "Which collection does NOT allow duplicate elements?", options: ["ArrayList", "LinkedList", "HashSet", "Vector"], correctAnswer: 2, explanation: "HashSet implements the Set interface which does not allow duplicate elements. It stores unique values only." },
    { question: "What is the difference between == and .equals() in Java?", options: ["No difference", "== compares references, .equals() compares content", "== compares content, .equals() compares references", "Both compare content"], correctAnswer: 1, explanation: "== checks if two references point to the same object in memory. .equals() compares the actual content/value of objects." },
    { question: "Which exception is thrown when dividing by zero in Java?", options: ["NullPointerException", "ArithmeticException", "IllegalArgumentException", "RuntimeException"], correctAnswer: 1, explanation: "An ArithmeticException with message 'by zero' is thrown when you divide an integer by zero in Java." },
    { question: "What does the 'final' keyword do when applied to a method?", options: ["The method cannot be called", "The method cannot be overridden", "The method runs only once", "The method returns a constant"], correctAnswer: 1, explanation: "A final method cannot be overridden by subclasses, ensuring consistent behavior across the class hierarchy." },
    { question: "Which interface must be implemented for a class to be used in a for-each loop?", options: ["Runnable", "Comparable", "Iterable", "Serializable"], correctAnswer: 2, explanation: "A class must implement the Iterable<T> interface (providing an iterator() method) to support the enhanced for-each loop." },
    { question: "What is autoboxing in Java?", options: ["Automatic memory management", "Automatic conversion between primitive types and wrapper classes", "Boxing of objects into arrays", "Automatic type casting"], correctAnswer: 1, explanation: "Autoboxing is the automatic conversion of primitive types (e.g., int) to their wrapper class equivalents (e.g., Integer) and vice versa." },
    { question: "Which keyword prevents a variable from being modified after initialization?", options: ["static", "final", "const", "immutable"], correctAnswer: 1, explanation: "The 'final' keyword makes a variable a constant — once assigned, its value cannot be changed." },
    { question: "What is the purpose of the 'synchronized' keyword in Java?", options: ["Improves performance", "Ensures only one thread executes a block at a time", "Defines a constant", "Creates a copy of an object"], correctAnswer: 1, explanation: "synchronized prevents race conditions by ensuring that only one thread can execute the synchronized block/method at a time." },
    { question: "What is a constructor in Java?", options: ["A method that returns the object type", "A special method called when an object is created", "A static method for class initialization", "A method to destroy objects"], correctAnswer: 1, explanation: "A constructor is a special method with the same name as the class that is automatically called when an object is instantiated." },
    { question: "Which of these is the parent class of all Java classes?", options: ["Base", "Object", "Class", "Super"], correctAnswer: 1, explanation: "java.lang.Object is the root class of the entire Java class hierarchy — every class implicitly extends Object." },
  ],

  "Database Management System": [
    { question: "Which SQL command is used to retrieve data from a database?", options: ["INSERT", "UPDATE", "SELECT", "FETCH"], correctAnswer: 2, explanation: "SELECT is the SQL command used to query and retrieve data from one or more database tables." },
    { question: "What does ACID stand for in database transactions?", options: ["Array, Control, Integrity, Data", "Atomicity, Consistency, Isolation, Durability", "Access, Commit, Index, Delete", "All, Create, Insert, Drop"], correctAnswer: 1, explanation: "ACID properties ensure reliable database transactions: Atomicity (all or nothing), Consistency (valid state), Isolation (independent), Durability (permanent)." },
    { question: "What is the primary purpose of normalization?", options: ["Speed up queries", "Reduce data redundancy and improve data integrity", "Increase storage capacity", "Add more columns to tables"], correctAnswer: 1, explanation: "Normalization organizes data to reduce redundancy and dependency by dividing large tables into smaller related ones." },
    { question: "Which normal form eliminates transitive dependencies?", options: ["1NF", "2NF", "3NF", "BCNF"], correctAnswer: 2, explanation: "Third Normal Form (3NF) eliminates transitive dependencies — non-key attributes must depend only on the primary key, not on other non-key attributes." },
    { question: "What is a foreign key?", options: ["A key used outside the database", "An attribute that references the primary key of another table", "A duplicate primary key", "An encrypted key for security"], correctAnswer: 1, explanation: "A foreign key is an attribute (or set of attributes) that references the primary key of another table, establishing a relationship between the tables." },
    { question: "Which JOIN returns all rows from both tables even when there is no match?", options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"], correctAnswer: 3, explanation: "FULL OUTER JOIN returns all rows from both tables, with NULL values where there is no matching row in either table." },
    { question: "What is an ER diagram used for?", options: ["Executing queries", "Visually representing the database structure and relationships", "Writing stored procedures", "Encrypting data"], correctAnswer: 1, explanation: "An Entity-Relationship (ER) diagram visually models the entities, attributes, and relationships in a database before implementation." },
    { question: "Which SQL aggregate function returns the number of rows?", options: ["SUM()", "MAX()", "COUNT()", "AVG()"], correctAnswer: 2, explanation: "COUNT() returns the number of rows that match the specified criteria. COUNT(*) counts all rows including NULLs." },
    { question: "What is a stored procedure?", options: ["A backup of the database", "A precompiled set of SQL statements stored in the database", "An external script that accesses the database", "A report generated by the database"], correctAnswer: 1, explanation: "A stored procedure is a set of precompiled SQL statements saved in the database that can be called with parameters to perform operations." },
    { question: "What does SQL stand for?", options: ["Structured Query Language", "Simple Query Logic", "Standard Question List", "System Query Language"], correctAnswer: 0, explanation: "SQL stands for Structured Query Language — the standard language for managing and manipulating relational databases." },
    { question: "Which of these is a NoSQL database?", options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"], correctAnswer: 2, explanation: "MongoDB is a document-oriented NoSQL database that stores data in flexible JSON-like documents rather than relational tables." },
    { question: "What is the purpose of an index in a database?", options: ["To add security", "To speed up data retrieval operations", "To store backup data", "To encrypt records"], correctAnswer: 1, explanation: "A database index is a data structure that improves the speed of data retrieval operations at the cost of additional storage space." },
  ],

  "Data Structure Using C": [
    { question: "Which data structure follows LIFO (Last In First Out) principle?", options: ["Queue", "Array", "Stack", "Linked List"], correctAnswer: 2, explanation: "A Stack follows the LIFO principle — the last element pushed onto the stack is the first one to be popped off." },
    { question: "What is the time complexity of binary search?", options: ["O(n)", "O(n²)", "O(log n)", "O(1)"], correctAnswer: 2, explanation: "Binary search has O(log n) time complexity — it halves the search space with each comparison on a sorted array." },
    { question: "Which traversal visits the root node first?", options: ["Inorder", "Postorder", "Preorder", "Level order"], correctAnswer: 2, explanation: "Preorder traversal visits: Root → Left → Right. Inorder is Left → Root → Right, Postorder is Left → Right → Root." },
    { question: "What is the main advantage of a linked list over an array?", options: ["Faster random access", "Dynamic size and easy insertion/deletion", "Less memory usage", "Better cache performance"], correctAnswer: 1, explanation: "Linked lists allow dynamic memory allocation — nodes can be easily inserted or deleted without shifting other elements as required in arrays." },
    { question: "In a min-heap, the minimum element is always at:", options: ["The last node", "Any leaf node", "The root node", "The middle node"], correctAnswer: 2, explanation: "In a min-heap, the root always contains the minimum element. Every parent node is less than or equal to its children." },
    { question: "Which sorting algorithm has the best average-case complexity?", options: ["Bubble Sort", "Selection Sort", "Merge Sort", "Insertion Sort"], correctAnswer: 2, explanation: "Merge Sort has O(n log n) average-case time complexity, making it one of the most efficient general-purpose sorting algorithms." },
    { question: "What data structure is used to implement BFS (Breadth-First Search)?", options: ["Stack", "Queue", "Tree", "Graph"], correctAnswer: 1, explanation: "BFS uses a Queue (FIFO) to process nodes level by level. DFS uses a Stack (FIFO)." },
    { question: "What is the time complexity of inserting an element at the beginning of an array of size n?", options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], correctAnswer: 2, explanation: "Inserting at the beginning requires shifting all n existing elements one position, resulting in O(n) time complexity." },
    { question: "A graph with no cycles is called a:", options: ["Tree", "DAG (Directed Acyclic Graph)", "Both A and B", "Planar Graph"], correctAnswer: 2, explanation: "Both a Tree (undirected, connected, acyclic) and a DAG (directed, acyclic) are graphs with no cycles." },
    { question: "Which of the following is not a linear data structure?", options: ["Array", "Stack", "Binary Tree", "Queue"], correctAnswer: 2, explanation: "A Binary Tree is a non-linear (hierarchical) data structure. Arrays, Stacks, and Queues are linear data structures." },
    { question: "What is the height of a complete binary tree with n nodes?", options: ["O(n)", "O(log n)", "O(n²)", "O(1)"], correctAnswer: 1, explanation: "A complete binary tree with n nodes has a height of O(log n), as each level doubles the number of nodes." },
    { question: "In quick sort, what is the worst-case time complexity?", options: ["O(n log n)", "O(log n)", "O(n²)", "O(n)"], correctAnswer: 2, explanation: "Quick Sort's worst case O(n²) occurs when the pivot is always the smallest or largest element, creating unbalanced partitions." },
  ],

  "Python Programming": [
    { question: "Which of the following is a mutable data type in Python?", options: ["String", "Tuple", "List", "Integer"], correctAnswer: 2, explanation: "Lists are mutable — you can add, remove, or change elements. Strings, tuples, and integers are immutable." },
    { question: "What does the 'self' parameter represent in a Python class method?", options: ["The parent class", "The current instance of the class", "A static variable", "The return value"], correctAnswer: 1, explanation: "'self' refers to the current instance of the class. It is the first parameter of every instance method in Python." },
    { question: "What is the output of: print(type([]) == list)?", options: ["False", "True", "Error", "None"], correctAnswer: 1, explanation: "type([]) returns <class 'list'>, and list is the list class. So they are equal, printing True." },
    { question: "Which method removes and returns the last element of a list?", options: ["remove()", "delete()", "pop()", "discard()"], correctAnswer: 2, explanation: "list.pop() removes and returns the last element by default. You can also use pop(index) to remove a specific index." },
    { question: "What is a lambda function in Python?", options: ["A function defined in a library", "An anonymous single-expression function", "A recursive function", "A built-in mathematical function"], correctAnswer: 1, explanation: "Lambda functions are anonymous functions defined with the 'lambda' keyword. They can take any number of arguments but have only one expression." },
    { question: "Which statement is used to handle exceptions in Python?", options: ["catch-throw", "try-except", "begin-rescue", "try-catch"], correctAnswer: 1, explanation: "Python uses try-except blocks to handle exceptions. The except block catches and handles the exception raised in the try block." },
    { question: "What does the 'with' statement do in Python?", options: ["Creates a new scope", "Ensures proper resource cleanup (context manager)", "Imports a module", "Creates a class"], correctAnswer: 1, explanation: "The 'with' statement ensures proper acquisition and release of resources (like file handles) using context managers, even if an error occurs." },
    { question: "Which built-in function returns the length of a string?", options: ["size()", "count()", "length()", "len()"], correctAnswer: 3, explanation: "len() is the built-in Python function that returns the number of characters in a string (or items in any sequence)." },
    { question: "What is a decorator in Python?", options: ["A function that modifies another function", "A design pattern for classes", "A visual styling tool", "A comment style"], correctAnswer: 0, explanation: "A decorator is a function that takes another function as argument, adds functionality, and returns the modified function using @syntax." },
    { question: "How do you create a virtual environment in Python?", options: ["python install venv", "pip create venv", "python -m venv venv", "pip install virtualenv --create"], correctAnswer: 2, explanation: "python -m venv <name> creates a virtual environment. Activate it with source <name>/bin/activate (Linux) or <name>\\Scripts\\activate (Windows)." },
    { question: "What is the difference between a list and a tuple?", options: ["Tuples can have duplicates, lists cannot", "Lists are mutable, tuples are immutable", "Tuples are faster to access than lists", "Lists use [] and tuples use {} brackets"], correctAnswer: 1, explanation: "Lists (defined with []) are mutable — their contents can change. Tuples (defined with ()) are immutable — once created, they cannot be modified." },
    { question: "Which of the following is used for multiple inheritance in Python?", options: ["class Child(Parent1, Parent2):", "class Child extends Parent1, Parent2:", "class Child inherits Parent1, Parent2:", "class Child: Parent1, Parent2"], correctAnswer: 0, explanation: "Python supports multiple inheritance natively: class Child(Parent1, Parent2): allows Child to inherit from both Parent1 and Parent2." },
  ],

  "Data Communication and Computer Network": [
    { question: "The OSI model has how many layers?", options: ["5", "6", "7", "4"], correctAnswer: 2, explanation: "The OSI (Open Systems Interconnection) model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application." },
    { question: "Which protocol is used to assign IP addresses dynamically?", options: ["DNS", "FTP", "DHCP", "SMTP"], correctAnswer: 2, explanation: "DHCP (Dynamic Host Configuration Protocol) automatically assigns IP addresses, subnet masks, and other network configuration to devices." },
    { question: "What is the purpose of ARP (Address Resolution Protocol)?", options: ["Translate domain names to IP addresses", "Map IP addresses to MAC addresses", "Encrypt network traffic", "Route packets between networks"], correctAnswer: 1, explanation: "ARP resolves an IP address to a corresponding MAC (hardware) address so packets can be delivered to the correct device on the local network." },
    { question: "TCP is a ________ protocol.", options: ["Connectionless", "Unreliable", "Connection-oriented", "Broadcast"], correctAnswer: 2, explanation: "TCP (Transmission Control Protocol) is connection-oriented — it establishes a connection (3-way handshake) before data transfer and ensures reliable delivery." },
    { question: "Which layer of the OSI model handles routing?", options: ["Data Link Layer", "Transport Layer", "Network Layer", "Session Layer"], correctAnswer: 2, explanation: "The Network Layer (Layer 3) is responsible for logical addressing (IP addresses) and routing packets between different networks." },
    { question: "What is the maximum segment size in Ethernet II frames?", options: ["1024 bytes", "1500 bytes", "2048 bytes", "4096 bytes"], correctAnswer: 1, explanation: "The Maximum Transmission Unit (MTU) for Ethernet frames is 1500 bytes (payload), with a total frame size of up to 1518 bytes including headers." },
    { question: "UDP differs from TCP in that UDP:", options: ["Is slower", "Is connection-oriented", "Does not guarantee delivery", "Uses 3-way handshake"], correctAnswer: 2, explanation: "UDP (User Datagram Protocol) is connectionless and does not guarantee delivery, ordering, or error checking — making it faster but less reliable." },
    { question: "Which device operates at Layer 2 (Data Link Layer) of the OSI model?", options: ["Router", "Hub", "Switch", "Repeater"], correctAnswer: 2, explanation: "A Switch operates at Layer 2, using MAC addresses to forward frames only to the appropriate port, unlike a hub which broadcasts to all ports." },
    { question: "What does HTTP stand for?", options: ["Hyper Text Transfer Protocol", "High Transfer Text Process", "Hyperlink Transfer and Transmission Protocol", "Host Transfer Text Protocol"], correctAnswer: 0, explanation: "HTTP (HyperText Transfer Protocol) is the foundation of data communication on the World Wide Web, operating at the Application Layer." },
    { question: "A subnet mask of 255.255.255.0 corresponds to which CIDR notation?", options: ["/16", "/24", "/8", "/32"], correctAnswer: 1, explanation: "255.255.255.0 means the first 24 bits are the network portion, written as /24 in CIDR notation. This allows 254 usable host addresses." },
    { question: "Which protocol is used for secure web browsing?", options: ["HTTP", "FTP", "HTTPS", "SMTP"], correctAnswer: 2, explanation: "HTTPS (HTTP Secure) uses SSL/TLS encryption to provide secure communication over a network, protecting data from interception." },
    { question: "What is the purpose of a firewall?", options: ["Speed up internet connection", "Monitor and control network traffic based on security rules", "Store network data", "Assign IP addresses"], correctAnswer: 1, explanation: "A firewall monitors incoming and outgoing network traffic and blocks unauthorized access based on predefined security rules." },
  ],

  "Software Engineering": [
    { question: "Which SDLC model follows a sequential linear approach?", options: ["Agile", "Spiral", "Waterfall", "RAD"], correctAnswer: 2, explanation: "The Waterfall model follows a strict sequential approach where each phase must complete before the next begins: Requirements → Design → Implementation → Testing → Maintenance." },
    { question: "In Agile, what is a 'Sprint'?", options: ["A bug fix release", "A time-boxed period to complete a set of tasks", "A deployment process", "A type of testing"], correctAnswer: 1, explanation: "A Sprint is a fixed time period (typically 1-4 weeks) in Scrum/Agile during which a specific set of features (backlog items) are developed and delivered." },
    { question: "What does UML stand for?", options: ["Universal Modelling Lifecycle", "Unified Modelling Language", "Universal Machine Language", "Unified Management Layer"], correctAnswer: 1, explanation: "UML (Unified Modeling Language) is a standardized visual language for designing and documenting software systems." },
    { question: "Which testing type verifies individual functions/modules in isolation?", options: ["Integration Testing", "System Testing", "Unit Testing", "Acceptance Testing"], correctAnswer: 2, explanation: "Unit Testing verifies individual components (functions, methods, classes) in isolation to ensure each unit works correctly on its own." },
    { question: "What is the purpose of version control systems like Git?", options: ["Compile code faster", "Track changes, enable collaboration, and maintain code history", "Test code automatically", "Deploy code to servers"], correctAnswer: 1, explanation: "Version control systems track changes to code over time, enable multiple developers to collaborate, and allow reverting to previous versions." },
    { question: "Which design principle states that a class should have only one reason to change?", options: ["Open/Closed Principle", "Liskov Substitution", "Single Responsibility Principle", "Interface Segregation"], correctAnswer: 2, explanation: "The Single Responsibility Principle (SRP) — part of SOLID — states every class should have one responsibility and only one reason to change." },
    { question: "What is a use case diagram used for?", options: ["Show database structure", "Model interactions between actors and system functionality", "Describe code algorithms", "Show class hierarchies"], correctAnswer: 1, explanation: "Use case diagrams show how different actors (users/systems) interact with the system's functionality, helping capture requirements." },
    { question: "What is the difference between functional and non-functional requirements?", options: ["No difference", "Functional defines what the system does; non-functional defines how well it does it", "Functional is for databases; non-functional is for UI", "Functional is mandatory; non-functional is optional"], correctAnswer: 1, explanation: "Functional requirements describe system behavior (features/functions). Non-functional requirements define quality attributes like performance, security, and usability." },
    { question: "Which methodology emphasizes continuous delivery and customer collaboration?", options: ["Waterfall", "V-Model", "Agile", "Big Bang"], correctAnswer: 2, explanation: "Agile methodology emphasizes iterative development, continuous delivery of working software, customer collaboration, and responding to change over rigid planning." },
    { question: "What is a Software Requirement Specification (SRS)?", options: ["A testing document", "A document that describes what the software should do", "A code review checklist", "A deployment script"], correctAnswer: 1, explanation: "An SRS is a detailed document describing the software's intended purpose, functionality, constraints, and behavior — the contract between developers and clients." },
    { question: "What is refactoring in software development?", options: ["Rewriting software from scratch", "Improving internal code structure without changing external behavior", "Adding new features to software", "Fixing critical bugs"], correctAnswer: 1, explanation: "Refactoring is the process of restructuring existing code to improve readability, reduce complexity, and maintainability without altering its external behavior." },
    { question: "Which Agile framework uses roles like Scrum Master, Product Owner, and Development Team?", options: ["Kanban", "XP (Extreme Programming)", "Scrum", "SAFe"], correctAnswer: 2, explanation: "Scrum defines three roles: Product Owner (manages backlog), Scrum Master (facilitates process), and Development Team (builds product)." },
  ],

  "Digital Techniques": [
    { question: "What is the binary equivalent of decimal 25?", options: ["11000", "11001", "10101", "11010"], correctAnswer: 1, explanation: "25 in binary: 25 = 16+8+1 = 2⁴+2³+2⁰ = 11001 in binary." },
    { question: "Which gate produces output 1 only when all inputs are 1?", options: ["OR gate", "NAND gate", "AND gate", "NOR gate"], correctAnswer: 2, explanation: "AND gate: output is 1 only when ALL inputs are 1. All other combinations produce 0." },
    { question: "What is the Boolean expression for a NOR gate with inputs A and B?", options: ["A + B", "A · B", "(A + B)'", "(A · B)'"], correctAnswer: 2, explanation: "NOR gate = NOT OR = complement of OR. For inputs A and B, NOR = (A + B)' (A OR B, then negated)." },
    { question: "A flip-flop is used for:", options: ["Amplifying signals", "Storing one bit of information", "Converting analog to digital", "Generating clock pulses"], correctAnswer: 1, explanation: "A flip-flop is a bistable circuit that can store one bit of data. It's the fundamental unit of sequential logic and memory." },
    { question: "Which number system uses base 16?", options: ["Binary", "Octal", "Decimal", "Hexadecimal"], correctAnswer: 3, explanation: "Hexadecimal (Hex) uses base 16 with digits 0-9 and letters A-F. It's widely used in computing to represent binary data compactly." },
    { question: "What is the 2's complement of 8-bit number 00001001?", options: ["11110111", "11110110", "00001001", "11111000"], correctAnswer: 0, explanation: "1's complement of 00001001 = 11110110. 2's complement = 11110110 + 1 = 11110111." },
    { question: "A Karnaugh map (K-map) is used for:", options: ["Binary to decimal conversion", "Boolean expression simplification", "Logic circuit testing", "Flip-flop design"], correctAnswer: 1, explanation: "K-maps are graphical tools used to simplify Boolean algebra expressions and minimize logic circuits systematically." },
    { question: "Which of the following is a universal gate?", options: ["AND gate", "OR gate", "NAND gate", "XOR gate"], correctAnswer: 2, explanation: "NAND and NOR are universal gates — any other logic gate (AND, OR, NOT, etc.) can be implemented using only NAND gates." },
    { question: "What is the hexadecimal representation of decimal 255?", options: ["FF", "FE", "EF", "F0"], correctAnswer: 0, explanation: "255 = 15×16 + 15 = 0xFF. F in hexadecimal = 15 in decimal. So 255 = FF in hexadecimal." },
    { question: "In digital electronics, what does TTL stand for?", options: ["Transistor-Transistor Logic", "Transfer Trigger Logic", "Transistor Transfer Level", "Tri-state Transistor Logic"], correctAnswer: 0, explanation: "TTL (Transistor-Transistor Logic) is a class of digital circuits built from bipolar junction transistors, common in logic chips like the 7400 series." },
    { question: "An SR latch is characterized by what problem?", options: ["High power consumption", "Forbidden state when both S and R are 1", "Slow switching speed", "Cannot store data"], correctAnswer: 1, explanation: "In an SR latch, setting both S=1 and R=1 creates an invalid/forbidden state with unpredictable output when both return to 0." },
    { question: "Which encoding technique uses more than two states to represent data?", options: ["Binary encoding", "NRZ", "Gray code", "Quaternary encoding"], correctAnswer: 3, explanation: "Quaternary encoding uses 4 states (levels) to represent data, allowing 2 bits per symbol, doubling the data rate compared to binary." },
  ],

  "Basic Mathematics": [
    { question: "What is the derivative of sin(x)?", options: ["-cos(x)", "cos(x)", "-sin(x)", "tan(x)"], correctAnswer: 1, explanation: "d/dx[sin(x)] = cos(x). This is a fundamental differentiation rule." },
    { question: "The determinant of a 2×2 matrix [[a,b],[c,d]] is:", options: ["a+d-b-c", "ac-bd", "ad-bc", "ab-cd"], correctAnswer: 2, explanation: "For a 2×2 matrix [[a,b],[c,d]], the determinant = ad - bc (product of main diagonal minus product of anti-diagonal)." },
    { question: "What is the integral of 1/x dx?", options: ["1/x²", "ln|x| + C", "x + C", "e^x + C"], correctAnswer: 1, explanation: "∫(1/x)dx = ln|x| + C. This is because the derivative of ln|x| is 1/x." },
    { question: "What is sin²(x) + cos²(x) equal to?", options: ["0", "2", "1", "sin(2x)"], correctAnswer: 2, explanation: "sin²(x) + cos²(x) = 1 is the Pythagorean identity — one of the most fundamental trigonometric identities." },
    { question: "The rank of a matrix is:", options: ["The number of rows", "The maximum number of linearly independent rows/columns", "The sum of all elements", "The number of non-zero elements"], correctAnswer: 1, explanation: "The rank of a matrix equals the maximum number of linearly independent rows (or columns), indicating the dimension of the row/column space." },
    { question: "What is the formula for the sum of an arithmetic series with n terms?", options: ["n(a + l)/2", "n × a", "n × l/2", "a × l/n"], correctAnswer: 0, explanation: "Sum of AP = n(a + l)/2 where a = first term, l = last term, n = number of terms. Also written as n/2[2a + (n-1)d]." },
    { question: "The solution to dy/dx = y is:", options: ["y = x + C", "y = Ce^x", "y = C·x", "y = e^x + C"], correctAnswer: 1, explanation: "Separating variables: dy/y = dx → ln|y| = x + C₁ → y = e^(x+C₁) = Ce^x where C = e^C₁." },
    { question: "What is lim(x→0) [sin(x)/x]?", options: ["0", "∞", "1", "Undefined"], correctAnswer: 2, explanation: "lim(x→0) sin(x)/x = 1. This is a fundamental limit used in calculus, provable by L'Hôpital's rule or geometric arguments." },
    { question: "The eigenvalues of matrix [[2,0],[0,3]] are:", options: ["2 and 3", "1 and 2", "0 and 1", "2 and 2"], correctAnswer: 0, explanation: "For a diagonal matrix, the eigenvalues are the diagonal elements themselves: 2 and 3." },
    { question: "What does the Fourier series represent?", options: ["A power series expansion", "A periodic function as a sum of sines and cosines", "The Taylor expansion of a function", "Matrix decomposition"], correctAnswer: 1, explanation: "Fourier series represents a periodic function as an infinite sum of sine and cosine functions of different frequencies." },
    { question: "What is the modulus of complex number 3+4i?", options: ["3", "4", "5", "7"], correctAnswer: 2, explanation: "|3+4i| = √(3² + 4²) = √(9+16) = √25 = 5. The modulus (absolute value) of a complex number a+bi is √(a²+b²)." },
    { question: "The value of e (Euler's number) is approximately:", options: ["3.14159", "2.71828", "1.41421", "1.73205"], correctAnswer: 1, explanation: "e ≈ 2.71828 is Euler's number, the base of natural logarithms. It appears naturally in continuous growth/decay problems." },
  ],

  "Engineering Mathematics I": [
    { question: "What is the derivative of e^x?", options: ["xe^(x-1)", "e^x", "ln(x)", "e^(x+1)"], correctAnswer: 1, explanation: "The derivative of e^x is itself: d/dx[e^x] = e^x. This is the unique property of the exponential function." },
    { question: "What is the gradient of scalar field f at a point?", options: ["A scalar value", "The maximum rate of change direction", "The curl of f", "The Laplacian of f"], correctAnswer: 1, explanation: "The gradient ∇f is a vector pointing in the direction of maximum rate of increase of f, with magnitude equal to that rate of increase." },
    { question: "Rolle's Theorem states that if f(a) = f(b), then:", options: ["f is constant on [a,b]", "There exists c in (a,b) where f'(c) = 0", "f is differentiable everywhere", "f has no extremum"], correctAnswer: 1, explanation: "Rolle's Theorem: if f is continuous on [a,b], differentiable on (a,b), and f(a) = f(b), then ∃c ∈ (a,b) such that f'(c) = 0." },
    { question: "The Laplace transform of 1 is:", options: ["1/s", "s", "1", "s²"], correctAnswer: 0, explanation: "L{1} = 1/s (for s > 0). This is a fundamental Laplace transform pair used in solving differential equations." },
    { question: "What is ∫₀^∞ e^(-st) dt equal to?", options: ["s", "1/s", "e^(-s)", "s²"], correctAnswer: 1, explanation: "∫₀^∞ e^(-st) dt = [-e^(-st)/s]₀^∞ = 0 - (-1/s) = 1/s. This is the Laplace transform of f(t)=1." },
    { question: "A square matrix A is called singular if:", options: ["det(A) ≠ 0", "det(A) = 0", "A is diagonal", "A = Aᵀ"], correctAnswer: 1, explanation: "A matrix is singular (non-invertible) when its determinant is zero. It means its rows/columns are linearly dependent." },
    { question: "The formula for Taylor series of f(x) around x = a is:", options: ["Σ f(n)(a)/n! · (x-a)ⁿ", "Σ f(x)ⁿ/n!", "f(a) + f(b)·x", "Σ xⁿ"], correctAnswer: 0, explanation: "Taylor series: f(x) = Σ [f⁽ⁿ⁾(a)/n!] · (x-a)ⁿ where f⁽ⁿ⁾(a) is the nth derivative of f evaluated at x = a." },
    { question: "The curl of a vector field F = (F₁, F₂, F₃) measures:", options: ["Divergence from a point", "Rotational tendency of the field", "Magnitude of the field", "Rate of change of magnitude"], correctAnswer: 1, explanation: "Curl measures the rotational tendency or circulation of a vector field around a point. If curl F = 0, the field is irrotational." },
    { question: "What is the period of sin(2πx)?", options: ["2π", "π", "1", "2"], correctAnswer: 2, explanation: "For sin(2πx), the period T = 2π/ω where ω = 2π, so T = 2π/2π = 1." },
    { question: "A matrix is called symmetric if:", options: ["A = -Aᵀ", "A = Aᵀ", "A = A⁻¹", "A² = I"], correctAnswer: 1, explanation: "A symmetric matrix equals its transpose: A = Aᵀ. This means element aᵢⱼ = aⱼᵢ for all i, j." },
    { question: "Green's theorem relates a line integral around a closed curve to:", options: ["A triple integral over a volume", "A surface integral over the enclosed region", "A double integral over the enclosed area", "Another line integral"], correctAnswer: 2, explanation: "Green's theorem relates the line integral around a simple closed curve C to a double integral over the plane region D bounded by C." },
    { question: "What is the result of the dot product of two perpendicular vectors?", options: ["1", "-1", "0", "The product of their magnitudes"], correctAnswer: 2, explanation: "The dot product A·B = |A||B|cos(θ). When θ = 90°, cos(90°) = 0, so the dot product of perpendicular vectors is 0." },
  ],

  "Engineering Physics": [
    { question: "What is the SI unit of force?", options: ["Watt", "Joule", "Newton", "Pascal"], correctAnswer: 2, explanation: "The Newton (N) is the SI unit of force. 1 N = 1 kg·m/s². Named after Sir Isaac Newton." },
    { question: "Which phenomenon explains why light bends when passing from one medium to another?", options: ["Reflection", "Refraction", "Diffraction", "Interference"], correctAnswer: 1, explanation: "Refraction is the bending of light as it passes from one medium to another due to a change in wave speed (described by Snell's Law)." },
    { question: "E = mc² represents:", options: ["Kinetic energy equation", "Mass-energy equivalence", "Electrostatic energy", "Gravitational potential energy"], correctAnswer: 1, explanation: "Einstein's mass-energy equivalence E = mc² shows that mass and energy are interchangeable, where c = speed of light (3×10⁸ m/s)." },
    { question: "The work done by a force is zero when:", options: ["Force is maximum", "Displacement is zero", "Velocity is constant", "Acceleration is positive"], correctAnswer: 1, explanation: "W = F·d·cos(θ). Work is zero when displacement d = 0 (or when the force is perpendicular to displacement, θ = 90°)." },
    { question: "Which type of wave requires a medium to propagate?", options: ["Electromagnetic waves", "Mechanical waves", "Radio waves", "Light waves"], correctAnswer: 1, explanation: "Mechanical waves (sound, water waves, seismic waves) require a physical medium to propagate. Electromagnetic waves can travel through a vacuum." },
    { question: "The principle of conservation of energy states that:", options: ["Energy cannot be created or destroyed, only transformed", "Energy is always lost as heat", "Kinetic energy equals potential energy always", "Total energy increases with time"], correctAnswer: 0, explanation: "Energy conservation: total energy in a closed system is constant. Energy can change form (KE ↔ PE, etc.) but the total remains constant." },
    { question: "According to Ohm's Law, V = I × R means:", options: ["Voltage is inversely proportional to current", "Voltage equals current times resistance", "Resistance is independent of voltage", "Current decreases with resistance"], correctAnswer: 1, explanation: "Ohm's Law: V = IR states that voltage (V) across a conductor equals the current (I) flowing through it times its resistance (R)." },
    { question: "The de Broglie wavelength is associated with:", options: ["The wavelength of light", "The wave nature of particles", "Sound wave frequency", "Electromagnetic spectrum"], correctAnswer: 1, explanation: "Louis de Broglie proposed that particles (like electrons) have wave-like properties. λ = h/mv, where h = Planck's constant, m = mass, v = velocity." },
    { question: "What is Young's modulus a measure of?", options: ["Shear stress", "Thermal expansion", "Material stiffness (elasticity)", "Magnetic permeability"], correctAnswer: 2, explanation: "Young's modulus (E) = Stress/Strain measures a material's stiffness/elasticity — how much it resists deformation under tension or compression." },
    { question: "The speed of light in a vacuum is approximately:", options: ["3×10⁶ m/s", "3×10⁸ m/s", "3×10¹⁰ m/s", "3×10⁴ m/s"], correctAnswer: 1, explanation: "The speed of light c ≈ 3×10⁸ m/s (approximately 300,000 km/s). This is the universal speed limit in physics." },
    { question: "Superconductivity is characterized by:", options: ["Infinite resistance at low temperatures", "Zero electrical resistance below a critical temperature", "Maximum magnetic permeability", "Maximum thermal conductivity"], correctAnswer: 1, explanation: "Superconductivity is the phenomenon where certain materials exhibit exactly zero electrical resistance below a critical temperature (Tc)." },
    { question: "The Heisenberg Uncertainty Principle states:", options: ["Energy and time cannot be measured simultaneously", "Position and momentum of a particle cannot both be precisely determined simultaneously", "Mass and velocity have an uncertainty relationship", "Charge and current are inversely related"], correctAnswer: 1, explanation: "Heisenberg's Uncertainty Principle: Δx·Δp ≥ ℏ/2. The more precisely we know a particle's position, the less precisely we can know its momentum, and vice versa." },
  ],

  "Programming in C": [
    { question: "What is the output of: printf(\"%d\", sizeof(int));", options: ["2", "4", "8", "Depends on compiler"], correctAnswer: 3, explanation: "The size of int depends on the platform and compiler: typically 2 bytes on 16-bit, 4 bytes on 32/64-bit systems. sizeof returns the correct size." },
    { question: "Which operator is used to access a structure member through a pointer?", options: [".", "->", "::", "&"], correctAnswer: 1, explanation: "The arrow operator (->) is used to access structure members through a pointer. ptr->member is equivalent to (*ptr).member." },
    { question: "What is a pointer in C?", options: ["A variable that stores data values", "A variable that stores the address of another variable", "A function parameter", "A type of array"], correctAnswer: 1, explanation: "A pointer is a variable that stores the memory address of another variable. It allows direct memory manipulation and efficient array handling." },
    { question: "What will be the output of: int a=5; printf(\"%d\", a++);", options: ["5", "6", "4", "Compilation error"], correctAnswer: 0, explanation: "a++ is post-increment: the current value (5) is used in the expression first, THEN incremented. So printf prints 5, and a becomes 6 afterward." },
    { question: "Which function is used to dynamically allocate memory in C?", options: ["new()", "alloc()", "malloc()", "memalloc()"], correctAnswer: 2, explanation: "malloc() (memory allocation) allocates a specified number of bytes at runtime and returns a void pointer to the allocated memory." },
    { question: "What is the purpose of the 'static' keyword in C?", options: ["Makes a variable constant", "Extends variable lifetime to the entire program execution", "Makes a function recursive", "Allocates memory on heap"], correctAnswer: 1, explanation: "A static local variable retains its value between function calls. A static global variable/function has internal linkage (only accessible within the file)." },
    { question: "What is recursion in C?", options: ["A function calling another function", "A function calling itself", "A loop that never ends", "Multiple return values"], correctAnswer: 1, explanation: "Recursion is when a function calls itself — directly or indirectly. It must have a base case to terminate." },
    { question: "The header file <string.h> provides which function?", options: ["printf()", "scanf()", "strcpy()", "malloc()"], correctAnswer: 2, explanation: "string.h provides string manipulation functions: strcpy(), strlen(), strcmp(), strcat(), etc. printf/scanf are in stdio.h." },
    { question: "What is the correct way to declare a 2D array in C?", options: ["int arr(3,4)", "int arr[3][4]", "int arr{3}{4}", "array int[3][4]"], correctAnswer: 1, explanation: "int arr[rows][cols] is the correct syntax for declaring a 2D array in C. Here int arr[3][4] declares a 3×4 integer array." },
    { question: "What does 'break' statement do inside a switch-case?", options: ["Ends the program", "Skips to the next case", "Exits the switch block", "Jumps to the top of switch"], correctAnswer: 2, explanation: "break exits the switch-case block. Without break, execution 'falls through' to the next case, executing it regardless of the case value." },
    { question: "Which storage class has the longest lifetime in C?", options: ["auto", "register", "static", "extern"], correctAnswer: 2, explanation: "static variables persist for the entire duration of the program. auto variables exist only within their block, register in CPU register, extern across files." },
    { question: "What is the purpose of the 'void' return type for a function?", options: ["Function returns zero", "Function takes no arguments", "Function does not return any value", "Function runs infinitely"], correctAnswer: 2, explanation: "A function with void return type doesn't return any value. It performs operations but has no meaningful result to return to the caller." },
  ],

  "Machine Learning": [
    { question: "Which algorithm is used for classification using decision boundaries?", options: ["K-Means", "Linear Regression", "Support Vector Machine", "PCA"], correctAnswer: 2, explanation: "SVM (Support Vector Machine) finds the optimal hyperplane that maximizes the margin between classes in the feature space." },
    { question: "What is overfitting in machine learning?", options: ["Model performs poorly on training data", "Model performs well on training but poorly on new/test data", "Model is too simple", "Model has too few parameters"], correctAnswer: 1, explanation: "Overfitting occurs when a model learns the training data too well (including noise), losing the ability to generalize to new, unseen data." },
    { question: "Which is an unsupervised learning algorithm?", options: ["Linear Regression", "Decision Trees", "K-Means Clustering", "Logistic Regression"], correctAnswer: 2, explanation: "K-Means is unsupervised — it discovers patterns/clusters in unlabeled data. Supervised algorithms (regression, decision trees) use labeled training data." },
    { question: "What does gradient descent minimize?", options: ["Training accuracy", "The loss/cost function", "The number of features", "Model complexity"], correctAnswer: 1, explanation: "Gradient descent is an optimization algorithm that iteratively adjusts model parameters to minimize the loss (cost) function." },
    { question: "What is the purpose of a train-test split?", options: ["Speed up training", "Evaluate model performance on unseen data", "Reduce dataset size", "Clean the data"], correctAnswer: 1, explanation: "Train-test split divides data into training set (model learning) and test set (evaluating generalization to unseen examples)." },
    { question: "Which activation function is commonly used in the output layer for binary classification?", options: ["ReLU", "Sigmoid", "Tanh", "Softmax"], correctAnswer: 1, explanation: "Sigmoid outputs values between 0 and 1, making it ideal for binary classification — interpreting the output as a probability." },
    { question: "What is the 'bias-variance tradeoff'?", options: ["Balancing model size and dataset size", "Trade-off between underfitting (high bias) and overfitting (high variance)", "Choosing between accuracy and speed", "Balance between features and samples"], correctAnswer: 1, explanation: "High bias = underfitting (too simple model). High variance = overfitting (too complex model). The goal is finding the sweet spot with minimal total error." },
    { question: "Which metric is used for evaluating regression models?", options: ["Accuracy", "F1-Score", "AUC-ROC", "Mean Squared Error (MSE)"], correctAnswer: 3, explanation: "MSE measures the average squared difference between predicted and actual values. Lower MSE = better regression model. RMSE is also common." },
    { question: "What is feature scaling and why is it needed?", options: ["Removing irrelevant features", "Normalizing features to a common scale for algorithms sensitive to magnitude", "Selecting the best features", "Encoding categorical variables"], correctAnswer: 1, explanation: "Feature scaling (normalization/standardization) brings features to a similar scale. Algorithms like SVM, KNN, and neural networks are sensitive to feature magnitudes." },
    { question: "What does PCA (Principal Component Analysis) do?", options: ["Classifies data into groups", "Reduces dimensionality while preserving maximum variance", "Increases the number of features", "Evaluates model accuracy"], correctAnswer: 1, explanation: "PCA is a dimensionality reduction technique that transforms data into a lower-dimensional space while preserving as much variance as possible." },
    { question: "Which of the following is a hyperparameter (not learned from data)?", options: ["Weights in neural network", "Slope in linear regression", "Number of trees in Random Forest", "Cluster centroids in K-Means"], correctAnswer: 2, explanation: "Hyperparameters are set before training (e.g., number of trees, learning rate, k in K-Means). Model parameters are learned during training from data." },
    { question: "Random Forest is an example of:", options: ["Single decision tree", "Ensemble learning", "Unsupervised clustering", "Deep learning"], correctAnswer: 1, explanation: "Random Forest is an ensemble method that builds multiple decision trees using random subsets of data and features, then aggregates their predictions (voting for classification, averaging for regression)." },
  ],

  "Cloud Computing": [
    { question: "Which cloud service model provides only infrastructure (VMs, storage, networking)?", options: ["SaaS", "PaaS", "IaaS", "FaaS"], correctAnswer: 2, explanation: "IaaS (Infrastructure as a Service) provides virtualized computing resources: virtual machines, storage, networking. Examples: AWS EC2, Google Compute Engine." },
    { question: "What does 'elasticity' mean in cloud computing?", options: ["Security of cloud data", "Ability to automatically scale resources up or down based on demand", "Physical flexibility of servers", "The geographic distribution of data centers"], correctAnswer: 1, explanation: "Elasticity is the ability to automatically provision and release resources dynamically to match current workload demands without manual intervention." },
    { question: "Which AWS service is used for object storage?", options: ["EC2", "RDS", "S3", "Lambda"], correctAnswer: 2, explanation: "Amazon S3 (Simple Storage Service) is an object storage service designed for storing and retrieving any amount of data from anywhere." },
    { question: "What is a container in cloud computing?", options: ["Physical server rack", "A virtual machine image", "A lightweight, isolated software package with its runtime environment", "A database storage unit"], correctAnswer: 2, explanation: "Containers (e.g., Docker) package application code with all its dependencies into a lightweight, portable unit that runs consistently across environments." },
    { question: "What does DevOps combine?", options: ["Development and Security", "Development and Operations", "Design and Operations", "Database and Operations"], correctAnswer: 1, explanation: "DevOps combines Development (Dev) and IT Operations (Ops) practices to shorten development cycles and provide continuous delivery of high-quality software." },
    { question: "Kubernetes is used for:", options: ["Cloud storage", "Container orchestration and management", "Database management", "Network security"], correctAnswer: 1, explanation: "Kubernetes (K8s) is an open-source container orchestration platform that automates deployment, scaling, and management of containerized applications." },
    { question: "What is serverless computing?", options: ["Computing without any servers", "Running code without managing server infrastructure (FaaS)", "A type of virtual machine", "Offline computing"], correctAnswer: 1, explanation: "Serverless (Function as a Service) allows developers to run code without provisioning servers. The cloud provider manages infrastructure. Examples: AWS Lambda, Azure Functions." },
    { question: "Which of these is a multi-cloud strategy?", options: ["Using only one cloud provider", "Using services from multiple cloud providers simultaneously", "Running applications on-premises", "Using only private cloud"], correctAnswer: 1, explanation: "Multi-cloud strategy involves using services from multiple cloud providers (AWS, Azure, GCP) to avoid vendor lock-in and leverage best-of-breed services." },
    { question: "What is SLA in cloud services?", options: ["Server Load Algorithm", "Service Level Agreement — uptime/performance guarantees", "Secure Login Architecture", "Storage Layer Architecture"], correctAnswer: 1, explanation: "SLA (Service Level Agreement) is a formal contract defining the level of service guaranteed, including uptime percentage (e.g., 99.9%), response times, and penalties." },
    { question: "What is the primary advantage of cloud computing over on-premises infrastructure?", options: ["Always cheaper", "No need for internet", "Pay-as-you-go model and reduced capital expenditure", "Higher performance always"], correctAnswer: 2, explanation: "Cloud computing offers a pay-as-you-go model (operational expenditure) vs. large upfront hardware investments (capital expenditure), plus flexibility and scalability." },
    { question: "What is load balancing in cloud?", options: ["Distributing workloads across multiple servers to optimize resource use", "Balancing the cloud billing", "Managing database loads", "Compressing data for storage"], correctAnswer: 0, explanation: "Load balancing distributes incoming network traffic across multiple backend servers to ensure no single server becomes a bottleneck, improving availability and responsiveness." },
    { question: "Which of the following is NOT a cloud deployment model?", options: ["Public Cloud", "Private Cloud", "Hybrid Cloud", "Universal Cloud"], correctAnswer: 3, explanation: "The three standard cloud deployment models are Public (shared infrastructure), Private (dedicated infrastructure), and Hybrid (combination). 'Universal Cloud' is not a recognized model." },
  ],

  "Web Page Designing": [
    { question: "What does HTML stand for?", options: ["Hyper Text Makeup Language", "Hyper Text Markup Language", "High Text Markup Language", "Hyper Transfer Markup Language"], correctAnswer: 1, explanation: "HTML (HyperText Markup Language) is the standard language for creating web pages, defining the structure and content." },
    { question: "Which CSS property changes the text color?", options: ["font-color", "text-color", "color", "foreground"], correctAnswer: 2, explanation: "The CSS 'color' property sets the text color. Example: color: #FF0000; makes text red." },
    { question: "What is the purpose of the <div> element?", options: ["Displays images", "Creates a block-level container for grouping elements", "Defines a heading", "Creates a hyperlink"], correctAnswer: 1, explanation: "<div> is a generic block-level container used to group HTML elements for styling with CSS or manipulation with JavaScript." },
    { question: "Which attribute is used to create a hyperlink in HTML?", options: ["link", "src", "href", "url"], correctAnswer: 2, explanation: "The 'href' (Hypertext Reference) attribute in the <a> tag specifies the URL: <a href='https://example.com'>Link</a>" },
    { question: "What does CSS stand for?", options: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style System", "Colorful Style Sheets"], correctAnswer: 1, explanation: "CSS (Cascading Style Sheets) is used to describe how HTML elements should be displayed — controlling layout, colors, fonts, etc." },
    { question: "Which HTML element is used for the largest heading?", options: ["<h6>", "<heading>", "<h1>", "<head>"], correctAnswer: 2, explanation: "<h1> to <h6> are HTML heading tags. <h1> is the largest/most important, <h6> is the smallest. They also affect SEO." },
    { question: "What is the correct HTML for creating a checkbox?", options: ["<input type='check'>", "<input type='checkbox'>", "<checkbox>", "<check>"], correctAnswer: 1, explanation: "<input type='checkbox'> creates a checkbox input element. Add 'checked' attribute to make it checked by default." },
    { question: "In CSS, what does 'display: flex' do?", options: ["Hides the element", "Makes element flexible for responsive layouts", "Creates a grid layout", "Floats the element left"], correctAnswer: 1, explanation: "display: flex enables Flexbox layout, making it easy to align and distribute space among items in a container (row or column direction)." },
    { question: "Which HTML tag is used to embed JavaScript in a page?", options: ["<js>", "<javascript>", "<script>", "<code>"], correctAnswer: 2, explanation: "The <script> tag is used to embed or reference JavaScript code in HTML. Can be placed in <head> or <body>." },
    { question: "What is a responsive web design?", options: ["Website that loads quickly", "Website that adapts its layout to different screen sizes", "Website with animations", "Website with dark mode support"], correctAnswer: 1, explanation: "Responsive web design uses flexible layouts, fluid images, and CSS media queries to make websites look and work well on all devices and screen sizes." },
    { question: "Which CSS selector targets all elements of class 'box'?", options: ["#box", "*box", ".box", "box:"], correctAnswer: 2, explanation: ".box (dot notation) selects all elements with class='box'. #box selects by ID. * selects all elements. .class is for class selectors." },
    { question: "What is the purpose of the <meta> tag in HTML?", options: ["Create navigation menus", "Provide metadata about the HTML document", "Add CSS styles", "Insert images"], correctAnswer: 1, explanation: "<meta> tags provide metadata (information about the page) like description, keywords, viewport settings, and character encoding — not displayed on page." },
  ],

  "Object Oriented Programming Using C++": [
    { question: "Which concept of OOP allows different classes to be treated as instances of the same class?", options: ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction"], correctAnswer: 2, explanation: "Polymorphism allows objects of different classes to be treated as objects of a common base class, enabling one interface to work with different types." },
    { question: "In C++, which keyword is used to define a class?", options: ["struct", "class", "type", "object"], correctAnswer: 1, explanation: "The 'class' keyword defines a class in C++. By default, members are private. 'struct' can also be used, but its members are public by default." },
    { question: "What is a constructor in C++?", options: ["A function that destroys an object", "A function automatically called when an object is created", "A function that copies objects", "A virtual function"], correctAnswer: 1, explanation: "A constructor has the same name as the class, no return type, and is automatically called when an object is instantiated to initialize it." },
    { question: "What is a destructor used for?", options: ["To create new objects", "To initialize class members", "To free resources when an object is destroyed", "To copy object data"], correctAnswer: 2, explanation: "A destructor (~ClassName) is called automatically when an object goes out of scope, releasing allocated memory or resources." },
    { question: "Which access specifier makes members accessible only within the class?", options: ["public", "protected", "private", "friend"], correctAnswer: 2, explanation: "private members are accessible only within the class itself — not by derived classes or outside code. This enforces encapsulation." },
    { question: "What is function overloading in C++?", options: ["Redefining a function in a derived class", "Defining multiple functions with the same name but different parameters", "Calling a function multiple times", "Using virtual functions"], correctAnswer: 1, explanation: "Function overloading defines multiple functions with the same name but different parameter types or counts — resolved at compile time." },
    { question: "What does the 'virtual' keyword enable in C++?", options: ["Compile-time polymorphism", "Runtime polymorphism via dynamic binding", "Function overloading", "Template specialization"], correctAnswer: 1, explanation: "virtual enables runtime polymorphism — when a virtual function is called through a base class pointer/reference, the derived class's version is called." },
    { question: "What is operator overloading?", options: ["Defining new operators", "Giving new meaning to existing operators for user-defined types", "Removing operator functionality", "Making operators work faster"], correctAnswer: 1, explanation: "Operator overloading allows standard C++ operators (+, -, ==, <<, etc.) to be redefined for user-defined classes." },
    { question: "In C++, 'this' pointer refers to:", options: ["The parent class object", "The current object instance", "The derived class object", "A static member"], correctAnswer: 1, explanation: "'this' is an implicit pointer available in non-static member functions, pointing to the object on which the function was called." },
    { question: "What is a pure virtual function?", options: ["A virtual function with an implementation", "A virtual function with no implementation, making the class abstract", "A private virtual function", "A static virtual function"], correctAnswer: 1, explanation: "A pure virtual function (= 0) has no implementation in the base class, making it abstract. Derived classes must override it to be concrete." },
    { question: "What is the difference between 'new' and 'malloc()' in C++?", options: ["No difference", "new calls constructor and is type-safe; malloc() only allocates raw memory", "malloc() is faster than new", "new is for arrays; malloc() is for single objects"], correctAnswer: 1, explanation: "new allocates memory AND calls the constructor, returning a typed pointer. malloc() only allocates raw bytes and returns void*, with no constructor call." },
    { question: "What is a template in C++?", options: ["A predefined class", "A mechanism to write generic code that works with any data type", "A design pattern", "A header file structure"], correctAnswer: 1, explanation: "Templates allow writing generic functions/classes that work with any data type. The compiler generates specific versions at compile time (compile-time polymorphism)." },
  ],

  "Applied Mathematics": [
    { question: "What is the rank of a matrix?", options: ["Number of rows", "Number of columns", "Maximum number of linearly independent rows/columns", "Sum of diagonal elements"], correctAnswer: 2, explanation: "The rank of a matrix is the maximum number of linearly independent rows (or columns), indicating the dimension of the row/column space." },
    { question: "Laplace transform of e^(at) is:", options: ["1/(s-a)", "1/(s+a)", "a/s²", "s/(s-a)"], correctAnswer: 0, explanation: "L{e^(at)} = 1/(s-a) for s > a. This is a fundamental Laplace transform pair used in solving differential equations." },
    { question: "What is the general solution of dy/dx + Py = Q (linear first-order ODE)?", options: ["y = e^(∫P dx)", "y·e^(∫P dx) = ∫Q·e^(∫P dx) dx + C", "y = Q/P", "y = ∫Q dx"], correctAnswer: 1, explanation: "The integrating factor method gives: multiply by e^(∫P dx), making left side d/dx[y·e^(∫P dx)] = Q·e^(∫P dx), then integrate both sides." },
    { question: "What is the curl of a gradient (∇×∇f)?", options: ["A non-zero vector", "Zero vector always", "The Laplacian", "Divergence of f"], correctAnswer: 1, explanation: "The curl of any gradient is always the zero vector: ∇×(∇f) = 0. This is because mixed partial derivatives are equal." },
    { question: "The formula for numerical integration using Simpson's 1/3 rule requires:", options: ["Odd number of intervals", "Even number of intervals", "Any number of intervals", "Prime number of intervals"], correctAnswer: 1, explanation: "Simpson's 1/3 rule requires an even number of subintervals (and odd number of points). Each application covers pairs of intervals." },
    { question: "Fourier series represents a function as:", options: ["Power series of x", "Sum of sines and cosines of multiples of a fundamental frequency", "Polynomial approximation", "Exponential series"], correctAnswer: 1, explanation: "Fourier series: f(x) = a₀/2 + Σ[aₙcos(nπx/L) + bₙsin(nπx/L)]. It expresses any periodic function as a sum of harmonics." },
    { question: "The eigenvalue equation is Ax = λx, where λ is found from:", options: ["det(A) = 0", "det(A - λI) = 0", "trace(A) = λ", "A + λI = 0"], correctAnswer: 1, explanation: "Eigenvalues are found by solving the characteristic equation det(A - λI) = 0. The resulting λ values are the eigenvalues of matrix A." },
    { question: "What is Cayley-Hamilton theorem?", options: ["Every matrix satisfies its own characteristic equation", "Every matrix is invertible", "Determinant equals trace", "Eigenvalues equal diagonal entries"], correctAnswer: 0, explanation: "The Cayley-Hamilton theorem states that every square matrix satisfies its own characteristic polynomial equation." },
    { question: "The inverse Laplace transform of 1/(s²+a²) is:", options: ["cos(at)/a", "sin(at)/a", "e^(at)", "a·sin(at)"], correctAnswer: 1, explanation: "L⁻¹{1/(s²+a²)} = sin(at)/a. This pair is essential in solving vibration and oscillation problems." },
    { question: "What is the condition for a system of equations Ax = b to have a unique solution?", options: ["det(A) = 0", "det(A) ≠ 0", "b = 0", "Rank(A) < n"], correctAnswer: 1, explanation: "A unique solution exists when det(A) ≠ 0 (A is non-singular/invertible). Then x = A⁻¹b uniquely." },
    { question: "Gauss elimination method is used to:", options: ["Find eigenvalues", "Solve systems of linear equations", "Integrate functions", "Differentiate matrices"], correctAnswer: 1, explanation: "Gauss elimination (row reduction) transforms a system Ax = b into upper triangular form using elementary row operations, then uses back substitution." },
    { question: "The order of a differential equation is defined by:", options: ["The highest degree of derivative", "The highest order derivative present", "The number of variables", "The number of solutions"], correctAnswer: 1, explanation: "The order of a differential equation is the order of the highest derivative in the equation. d²y/dx² has order 2." },
  ],

  "Microprocessor Programming": [
    { question: "What is the word length of the 8085 microprocessor?", options: ["4-bit", "8-bit", "16-bit", "32-bit"], correctAnswer: 1, explanation: "The 8085 is an 8-bit microprocessor — it processes 8 bits of data at a time. Its address bus is 16-bit, allowing 64KB of memory." },
    { question: "Which register in 8085 is called the accumulator?", options: ["B register", "H register", "A register", "PC register"], correctAnswer: 2, explanation: "The A register (Accumulator) is the primary register in 8085. All arithmetic and logical operations use A as the implied source/destination." },
    { question: "The Program Counter (PC) in a microprocessor:", options: ["Counts programs", "Holds the address of the next instruction to be executed", "Stores the result of arithmetic operations", "Counts the number of instructions"], correctAnswer: 1, explanation: "The Program Counter always points to the memory address of the next instruction to be fetched and executed." },
    { question: "What is the function of the Stack Pointer (SP)?", options: ["Points to the top of the stack in memory", "Stores program data", "Counts stack operations", "Holds the starting address of program"], correctAnswer: 0, explanation: "The Stack Pointer holds the memory address of the top of the stack. PUSH decrements SP; POP increments SP." },
    { question: "In 8085, how many general purpose register pairs are available?", options: ["2", "3", "4", "5"], correctAnswer: 1, explanation: "8085 has three 16-bit register pairs: BC, DE, and HL. These can hold 16-bit data or memory addresses." },
    { question: "What does the instruction 'MOV A, B' do in 8085?", options: ["Moves content of A to B", "Moves content of B to A", "Swaps A and B", "Adds A and B"], correctAnswer: 1, explanation: "MOV destination, source — MOV A, B copies the content of register B into register A." },
    { question: "Which flag is set when the result of an arithmetic operation is zero?", options: ["Carry flag", "Sign flag", "Zero flag", "Parity flag"], correctAnswer: 2, explanation: "The Zero flag (Z) is set to 1 when the result of an operation is 0x00. It is used in conditional jumps like JZ (Jump if Zero)." },
    { question: "What is the purpose of the instruction 'CALL' in 8085?", options: ["Calls operating system", "Pushes PC to stack and jumps to subroutine", "Copies register values", "Clears accumulator"], correctAnswer: 1, explanation: "CALL saves the return address (next PC value) onto the stack, then transfers control to the specified subroutine address." },
    { question: "The 8086 microprocessor has a data bus width of:", options: ["8-bit", "16-bit", "32-bit", "64-bit"], correctAnswer: 1, explanation: "The 8086 is a 16-bit microprocessor with a 16-bit data bus and 20-bit address bus (allowing 1MB memory addressing)." },
    { question: "In assembly language, the mnemonic 'JNC' stands for:", options: ["Jump if No Carry", "Jump if Negative Count", "Jump if Not Complete", "Jump if New Condition"], correctAnswer: 0, explanation: "JNC (Jump if No Carry) is a conditional jump instruction that transfers control to the specified address only if the Carry flag is 0." },
    { question: "What does ALE (Address Latch Enable) signal do in 8085?", options: ["Enables memory access", "Demultiplexes address and data bus", "Controls interrupt priority", "Enables arithmetic operations"], correctAnswer: 1, explanation: "8085 multiplexes the lower 8 address bits with the 8-bit data bus. ALE is used to latch the lower address byte into an external latch." },
    { question: "Which instruction adds the content of register B to accumulator A in 8085?", options: ["MOV A, B", "ADD B", "SUB B", "CMP B"], correctAnswer: 1, explanation: "ADD B adds the content of register B to the accumulator A and stores the result in A. The result affects all flags." },
  ],

  "Computer Graphics": [
    { question: "Which algorithm is used to draw a circle in computer graphics?", options: ["Bresenham's Line Algorithm", "Midpoint Circle Algorithm", "Flood Fill Algorithm", "Scan Line Algorithm"], correctAnswer: 1, explanation: "The Midpoint Circle Algorithm (also related to Bresenham's Circle Algorithm) uses integer arithmetic to draw circles efficiently on a raster display." },
    { question: "What does 'rasterization' mean in graphics?", options: ["Converting 3D models to 2D", "Converting vector graphics to pixel-based representation", "Applying textures to polygons", "Removing hidden surfaces"], correctAnswer: 1, explanation: "Rasterization converts vector/geometric shapes (lines, curves, polygons) into a raster image (a grid of pixels) for display." },
    { question: "DDA stands for:", options: ["Digital Drawing Algorithm", "Digital Differential Analyzer", "Direct Display Algorithm", "Dynamic Drawing Approach"], correctAnswer: 1, explanation: "DDA (Digital Differential Analyzer) is a line drawing algorithm that calculates the intermediate positions by incrementing x and computing y = mx + b." },
    { question: "In a 2D transformation, what matrix represents rotation by angle θ?", options: ["[[cos θ, sin θ], [-sin θ, cos θ]]", "[[cos θ, -sin θ], [sin θ, cos θ]]", "[[1, 0], [0, 1]]", "[[θ, 0], [0, θ]]"], correctAnswer: 1, explanation: "The 2D rotation matrix is [[cosθ, -sinθ], [sinθ, cosθ]], which rotates points counterclockwise by angle θ about the origin." },
    { question: "Which technique is used to remove surfaces not visible to the viewer?", options: ["Anti-aliasing", "Hidden surface removal", "Texture mapping", "Morphing"], correctAnswer: 1, explanation: "Hidden surface removal (or visible surface determination) algorithms like Z-buffer and BSP trees eliminate surfaces hidden behind other objects." },
    { question: "RGB color model uses:", options: ["Subtractive color mixing", "Additive color mixing", "Hue-based mixing", "CMYK mixing"], correctAnswer: 1, explanation: "RGB (Red, Green, Blue) uses additive color mixing — combining colored light. Full intensities of R+G+B produce white." },
    { question: "Bresenham's line algorithm uses:", options: ["Floating point arithmetic only", "Only integer arithmetic", "Trigonometric functions", "Matrix operations"], correctAnswer: 1, explanation: "Bresenham's algorithm uses only integer arithmetic (additions, subtractions) making it very fast and hardware-friendly for drawing lines." },
    { question: "What is clipping in computer graphics?", options: ["Reducing image resolution", "Removing parts of objects outside the viewing area", "Smoothing jagged edges", "Applying color filters"], correctAnswer: 1, explanation: "Clipping removes parts of a scene that fall outside the view volume/clipping window, improving rendering efficiency and correctness." },
    { question: "Bezier curves are defined by:", options: ["Mathematical equations only", "Control points that influence the curve shape", "Pixel coordinates directly", "Raster scan patterns"], correctAnswer: 1, explanation: "Bezier curves are defined by control points. The curve is attracted to but doesn't necessarily pass through interior control points." },
    { question: "Which projection preserves parallel lines and doesn't show depth foreshortening?", options: ["Perspective projection", "Orthographic projection", "Isometric projection", "Oblique projection"], correctAnswer: 1, explanation: "Orthographic projection projects objects along lines parallel to the view direction. Parallel lines remain parallel and there's no depth foreshortening." },
    { question: "Anti-aliasing is used to:", options: ["Speed up rendering", "Reduce jagged edges (jaggies) on diagonal lines and curves", "Add texture effects", "Remove hidden surfaces"], correctAnswer: 1, explanation: "Anti-aliasing smooths staircase-like jagged edges on diagonal lines, curves, and text by blending pixel colors at boundaries." },
    { question: "The Z-buffer algorithm is used for:", options: ["Color interpolation", "Hidden surface removal based on depth values", "Texture mapping", "Lighting calculations"], correctAnswer: 1, explanation: "The Z-buffer (depth buffer) stores depth (z) values for each pixel. When multiple polygons cover the same pixel, only the closest (smallest z) is displayed." },
  ],

  "Engineering Mechanics": [
    { question: "A body is in equilibrium when:", options: ["Net force is maximum", "Net force and net moment are both zero", "Velocity is constant", "Acceleration is uniform"], correctAnswer: 1, explanation: "For static equilibrium: ΣF = 0 (sum of all forces is zero) AND ΣM = 0 (sum of all moments is zero)." },
    { question: "The moment of a force about a point equals:", options: ["Force × distance (perpendicular)", "Force + distance", "Force / distance", "Force × velocity"], correctAnswer: 0, explanation: "Moment (torque) = Force × perpendicular distance from the point to the line of action of the force. Units: N·m." },
    { question: "Lami's theorem applies when:", options: ["Two forces are in equilibrium", "Three concurrent coplanar forces are in equilibrium", "Multiple parallel forces act", "Forces form a closed triangle"], correctAnswer: 1, explanation: "Lami's theorem: when three concurrent coplanar forces are in equilibrium, each force is proportional to the sine of the angle between the other two." },
    { question: "The centroid of a uniform triangular lamina from its base is:", options: ["H/2", "H/3", "H/4", "2H/3"], correctAnswer: 1, explanation: "The centroid of a triangle is at H/3 from the base (or 2H/3 from the apex), where H is the height." },
    { question: "What is the coefficient of friction?", options: ["Normal force / Friction force", "Friction force / Normal force", "Total force / Area", "Weight / Mass"], correctAnswer: 1, explanation: "μ = F_friction / N (Normal force). It's dimensionless and represents the ratio of maximum friction to normal force." },
    { question: "Newton's second law states:", options: ["F = mv", "F = ma", "F = m/a", "F = v/t"], correctAnswer: 1, explanation: "Newton's second law: F = ma. Net force equals mass times acceleration. This is the fundamental law of dynamics." },
    { question: "The principle of virtual work states that:", options: ["Work done is always positive", "For a system in equilibrium, virtual work is zero for any virtual displacement", "Kinetic energy equals potential energy", "Power = Work × Time"], correctAnswer: 1, explanation: "Virtual work principle: if a system is in equilibrium, the total virtual work done by all forces during a virtual displacement is zero." },
    { question: "Radius of gyration (k) relates to moment of inertia (I) and area (A) as:", options: ["k = I/A", "k = √(I/A)", "k = A/I", "k = I × A"], correctAnswer: 1, explanation: "k = √(I/A) where I is the moment of inertia and A is the area (or mass). It represents the distance from the axis where the area/mass could be concentrated." },
    { question: "A projectile's horizontal velocity component:", options: ["Increases throughout flight", "Decreases throughout flight", "Remains constant throughout flight", "Reverses direction at peak"], correctAnswer: 2, explanation: "Horizontal velocity remains constant throughout projectile motion (ignoring air resistance) since gravity acts only vertically." },
    { question: "The work-energy theorem states:", options: ["Work = Force × Time", "Net work done = Change in kinetic energy", "Work = Force × Displacement in any direction", "Total work is conserved"], correctAnswer: 1, explanation: "Work-energy theorem: W_net = ΔKE = ½mv₂² - ½mv₁². The net work done on an object equals the change in its kinetic energy." },
    { question: "What is the angle of friction?", options: ["Angle between reaction and normal force at limiting friction", "Angle of inclined plane", "Angle at which object slides", "Angle between friction and applied force"], correctAnswer: 0, explanation: "The angle of friction (φ) is the angle between the resultant reaction R and the normal force N when friction is at its limiting value: tan(φ) = μ." },
    { question: "Impulse-momentum theorem states:", options: ["Impulse = Force × Distance", "Impulse = Change in momentum", "Impulse = mass × velocity", "Impulse = Work done"], correctAnswer: 1, explanation: "Impulse = F × Δt = Δ(mv) = Change in momentum. This explains why longer contact time reduces impact force (like airbags)." },
  ],

  "Strength of Materials": [
    { question: "Stress is defined as:", options: ["Force × Area", "Force / Area", "Force × Length", "Deformation / Length"], correctAnswer: 1, explanation: "Stress (σ) = Force (F) / Area (A). It is the internal resisting force per unit area within a material. Units: Pa or N/m²." },
    { question: "Strain is defined as:", options: ["Force per unit area", "Change in length / Original length", "Change in volume / Original volume", "Load per unit mass"], correctAnswer: 1, explanation: "Longitudinal strain (ε) = ΔL/L (change in length / original length). It is dimensionless." },
    { question: "Young's Modulus (E) is the ratio of:", options: ["Shear stress to shear strain", "Lateral strain to longitudinal strain", "Normal stress to normal strain", "Pressure to volumetric strain"], correctAnswer: 2, explanation: "Young's Modulus E = σ/ε = Stress/Strain. It measures a material's stiffness (resistance to elastic deformation)." },
    { question: "The bending moment is maximum where:", options: ["Shear force is maximum", "Shear force is zero (changes sign)", "Bending moment diagram crosses zero", "Load intensity is maximum"], correctAnswer: 1, explanation: "BM is maximum where the shear force changes sign (SFD crosses zero). This is a critical design point." },
    { question: "Poisson's ratio (ν) is:", options: ["Longitudinal strain / Lateral strain", "Lateral strain / Longitudinal strain", "Shear stress / Shear strain", "Young's modulus / Bulk modulus"], correctAnswer: 1, explanation: "ν = -Lateral strain / Longitudinal strain. When pulled axially, materials contract laterally. Poisson's ratio is typically 0.25-0.35 for metals." },
    { question: "In a simply supported beam with central point load W, maximum bending moment is:", options: ["WL/4", "WL/8", "WL/2", "WL"], correctAnswer: 0, explanation: "For a simply supported beam with central point load W and span L: M_max = WL/4 at mid-span." },
    { question: "Shear stress distribution in a rectangular beam cross-section is:", options: ["Linear from top to bottom", "Parabolic with maximum at neutral axis", "Uniform throughout", "Maximum at top and bottom"], correctAnswer: 1, explanation: "Shear stress in a rectangular cross-section has a parabolic distribution, with maximum at the neutral axis (centroid) and zero at extreme fibers." },
    { question: "What is the section modulus (Z) of a cross-section?", options: ["I × y_max", "I / y_max", "A × r²", "M / σ"], correctAnswer: 1, explanation: "Section modulus Z = I/y_max where I is the moment of inertia and y_max is the distance from neutral axis to extreme fiber. M = σ × Z." },
    { question: "Euler's formula for critical load of a column is:", options: ["P_cr = π²EI/L²", "P_cr = EI/L", "P_cr = AE/L", "P_cr = πEI/4L²"], correctAnswer: 0, explanation: "Euler's critical load: P_cr = π²EI/L_eff², where L_eff depends on end conditions. For both ends pinned: L_eff = L." },
    { question: "What is the relationship between Modulus of Elasticity (E), Modulus of Rigidity (G), and Poisson's ratio (ν)?", options: ["G = E/3(1-ν)", "G = E/2(1+ν)", "G = E/(1+2ν)", "G = 2E/(1+ν)"], correctAnswer: 1, explanation: "G = E/[2(1+ν)]. This elastic relationship connects Young's modulus, shear modulus, and Poisson's ratio." },
    { question: "In thin cylinders, hoop stress (circumferential) is:", options: ["pd/4t", "pd/2t", "pd/t", "2pd/t"], correctAnswer: 1, explanation: "Hoop (circumferential) stress σ_h = pd/2t, where p = internal pressure, d = diameter, t = wall thickness. It's twice the longitudinal stress." },
    { question: "Factor of safety is defined as:", options: ["Working stress / Ultimate stress", "Ultimate stress / Working stress", "Ultimate load / Applied load", "Both B and C"], correctAnswer: 3, explanation: "FoS = Ultimate stress / Working (permissible) stress = Ultimate load / Working load. It represents the margin of safety against failure." },
  ],

  "Linux Basics": [
    { question: "Which command is used to list files in a directory?", options: ["dir", "ls", "list", "show"], correctAnswer: 1, explanation: "ls (list) shows files in the current directory. ls -la shows hidden files with details. This is the most fundamental Linux command." },
    { question: "What does 'chmod 755 filename' do?", options: ["Sets read-only permission", "Gives owner rwx, group and others rx permissions", "Removes all permissions", "Makes file executable only"], correctAnswer: 1, explanation: "chmod 755: 7(rwx) for owner, 5(r-x) for group, 5(r-x) for others. Numbers represent: r=4, w=2, x=1." },
    { question: "Which command shows the current working directory?", options: ["pwd", "cwd", "dir", "where"], correctAnswer: 0, explanation: "pwd (Print Working Directory) displays the full absolute path of the current directory you're in." },
    { question: "The command 'grep -r pattern /dir' does what?", options: ["Replaces pattern in files", "Searches for pattern in files recursively", "Removes pattern from files", "Gets file permissions"], correctAnswer: 1, explanation: "grep searches for a pattern in files. -r (recursive) searches all files in the directory and its subdirectories." },
    { question: "In Linux, what does the pipe operator '|' do?", options: ["Deletes output", "Sends output of one command as input to another", "Runs commands in parallel", "Prints to file"], correctAnswer: 1, explanation: "The pipe | redirects stdout of the left command to stdin of the right command. Example: ls -la | grep .txt" },
    { question: "Which command creates a new directory?", options: ["touch", "create", "mkdir", "newdir"], correctAnswer: 2, explanation: "mkdir (make directory) creates a new directory. mkdir -p creates nested directories including parent directories." },
    { question: "What is the root user in Linux?", options: ["The first user created", "The user in the /root directory", "The superuser with all administrative privileges", "A read-only user"], correctAnswer: 2, explanation: "root is the superuser in Linux with UID 0 and unlimited privileges. It can read/write/execute any file and perform all system operations." },
    { question: "Which command displays the first 10 lines of a file?", options: ["tail file", "head file", "first file", "top file"], correctAnswer: 1, explanation: "head displays the first 10 lines of a file by default. head -n 20 shows the first 20 lines. tail shows the last 10 lines." },
    { question: "What does 'ps aux' command display?", options: ["Power settings", "All running processes with details", "Process scheduling", "System performance"], correctAnswer: 1, explanation: "ps aux lists all running processes for all users with details like PID, CPU usage, memory usage, and command name." },
    { question: "The cron job syntax '0 9 * * 1-5 /script.sh' means:", options: ["Run every 9 minutes", "Run at 9 AM on weekdays (Monday-Friday)", "Run every hour", "Run on 9th of every month"], correctAnswer: 1, explanation: "Cron format: minute hour day month weekday. 0 9 * * 1-5 = at minute 0, hour 9, every day, every month, Monday-Friday." },
    { question: "Which command shows disk usage of files and directories?", options: ["df", "du", "disk", "size"], correctAnswer: 1, explanation: "du (disk usage) shows disk space used by files/directories. du -sh * shows sizes of items in current directory. df shows filesystem disk space usage." },
    { question: "What does 'sudo' do in Linux?", options: ["Switch user and delete", "Execute command with superuser (root) privileges", "Show user details", "Search file system"], correctAnswer: 1, explanation: "sudo (Superuser Do) allows permitted users to run commands as root or another user. It's safer than logging in as root directly." },
  ],

  "Fluid Mechanics": [
    { question: "Pascal's Law states that:", options: ["Pressure decreases with depth", "Pressure applied to a fluid is transmitted equally in all directions", "Fluid pressure depends on container shape", "Velocity increases when area decreases"], correctAnswer: 1, explanation: "Pascal's Law: pressure applied at one point in a confined fluid is transmitted equally throughout the fluid in all directions." },
    { question: "Bernoulli's equation relates:", options: ["Temperature and pressure", "Pressure, velocity, and elevation in fluid flow", "Viscosity and flow rate", "Density and temperature"], correctAnswer: 1, explanation: "Bernoulli's: P + ½ρv² + ρgh = constant along a streamline (for ideal, inviscid, steady flow). It represents conservation of energy in fluid flow." },
    { question: "Reynolds number (Re) determines:", options: ["Fluid density", "Whether flow is laminar or turbulent", "Fluid viscosity", "Pressure drop in pipes"], correctAnswer: 1, explanation: "Re = ρvD/μ (density × velocity × diameter / dynamic viscosity). Re < 2000: laminar; Re > 4000: turbulent; 2000-4000: transitional." },
    { question: "Continuity equation in fluid flow states:", options: ["Energy is conserved", "Mass flow rate is constant (ρ₁A₁v₁ = ρ₂A₂v₂)", "Pressure is constant", "Temperature is uniform"], correctAnswer: 1, explanation: "Continuity equation: ρ₁A₁v₁ = ρ₂A₂v₂. For incompressible flow: A₁v₁ = A₂v₂. It represents conservation of mass in a control volume." },
    { question: "What is hydraulic grade line (HGL)?", options: ["Line connecting pressure head + datum head", "Line connecting velocity head + datum head", "Line showing maximum flow", "Pipe centerline"], correctAnswer: 0, explanation: "HGL represents (P/ρg + z) — pressure head plus datum head. It shows where water would rise in a piezometer tube." },
    { question: "The viscosity of a fluid is:", options: ["Its tendency to resist flow", "Its density per unit volume", "Its surface tension", "Its compressibility"], correctAnswer: 0, explanation: "Dynamic viscosity (μ) is the measure of a fluid's resistance to flow/deformation. High viscosity = thick fluid (honey). Low viscosity = thin fluid (water)." },
    { question: "The velocity of flow in a pipe increases when the pipe area:", options: ["Increases", "Decreases", "Remains the same", "Changes shape"], correctAnswer: 1, explanation: "From continuity equation A₁v₁ = A₂v₂, when area decreases, velocity must increase to maintain constant flow rate (like narrowing a hose nozzle)." },
    { question: "Darcy-Weisbach equation is used to calculate:", options: ["Fluid velocity", "Head loss due to friction in pipes", "Reynolds number", "Buoyancy force"], correctAnswer: 1, explanation: "Darcy-Weisbach: hf = f(L/D)(v²/2g), where f = friction factor, L = pipe length, D = diameter, v = velocity. It calculates friction head losses in pipes." },
    { question: "Archimedes' principle states that buoyant force equals:", options: ["Volume of object × density of fluid", "Weight of fluid displaced by the object", "Surface area × pressure", "Mass of object × gravity"], correctAnswer: 1, explanation: "Buoyant force = Weight of fluid displaced = ρ_fluid × V_submerged × g. An object floats when this equals or exceeds its weight." },
    { question: "A venturimeter is used to measure:", options: ["Fluid pressure", "Fluid flow rate (velocity)", "Fluid density", "Pipe diameter"], correctAnswer: 1, explanation: "A venturimeter measures flow rate by measuring pressure difference between inlet and throat. Using Bernoulli's equation: Q = Cd × A × √(2gh/(1-(A2/A1)²))." },
    { question: "What is the unit of kinematic viscosity?", options: ["Pa·s", "N/m²", "m²/s (Stokes)", "kg/m·s"], correctAnswer: 2, explanation: "Kinematic viscosity ν = μ/ρ has units m²/s (or Stokes, cm²/s). Dynamic viscosity μ has units Pa·s or N·s/m²." },
    { question: "In turbulent flow, the velocity profile across a pipe is:", options: ["Parabolic", "Flatter/more uniform than laminar", "Linear", "Uniform (plug flow)"], correctAnswer: 1, explanation: "Turbulent flow has a flatter (blunter) velocity profile compared to the parabolic profile of laminar flow, due to mixing of fluid layers." },
  ],

  "default": [
    { question: "Which of the following is an example of a renewable energy source?", options: ["Coal", "Natural Gas", "Solar Energy", "Nuclear Energy"], correctAnswer: 2, explanation: "Solar energy is renewable — it comes from the sun and is inexhaustible on human timescales." },
    { question: "What is the purpose of version control?", options: ["To speed up code", "To track and manage changes to code over time", "To compile code faster", "To deploy applications"], correctAnswer: 1, explanation: "Version control systems like Git track changes to files over time, allowing collaboration, rollback, and branch management." },
    { question: "What does API stand for?", options: ["Application Programming Interface", "Advanced Programming Input", "Automated Process Integration", "Application Process Input"], correctAnswer: 0, explanation: "API (Application Programming Interface) defines how software components interact, enabling different systems to communicate with each other." },
    { question: "What is the binary representation of decimal 10?", options: ["1001", "1010", "1100", "1011"], correctAnswer: 1, explanation: "10 in binary: 10 = 8+2 = 2³+2¹ = 1010 in binary." },
    { question: "Which protocol sends email?", options: ["HTTP", "FTP", "SMTP", "POP3"], correctAnswer: 2, explanation: "SMTP (Simple Mail Transfer Protocol) is used to send email. POP3 and IMAP are used to receive email." },
    { question: "What is an algorithm?", options: ["A computer program", "A step-by-step procedure to solve a problem", "A data structure", "A type of hardware"], correctAnswer: 1, explanation: "An algorithm is a finite set of well-defined instructions for solving a problem or accomplishing a task." },
    { question: "What is the Internet of Things (IoT)?", options: ["The worldwide internet", "Network of physical devices connected to the internet", "A type of cloud service", "Social media platform"], correctAnswer: 1, explanation: "IoT refers to the network of physical objects (devices, vehicles, appliances) embedded with sensors and connectivity to exchange data over the internet." },
    { question: "What is RAM used for?", options: ["Long-term data storage", "Temporary working memory for active programs", "Storing the operating system permanently", "Network communication"], correctAnswer: 1, explanation: "RAM (Random Access Memory) is temporary, volatile memory that stores data and programs currently in use by the CPU." },
    { question: "What does a compiler do?", options: ["Runs programs", "Translates source code to machine code", "Stores data", "Connects to the internet"], correctAnswer: 1, explanation: "A compiler translates high-level source code (C, Java) into machine code or bytecode that a computer can execute." },
    { question: "What is cybersecurity?", options: ["Physical security of computers", "Protection of computer systems and data from unauthorized access/attacks", "Internet speed optimization", "Cloud storage management"], correctAnswer: 1, explanation: "Cybersecurity is the practice of protecting computer systems, networks, and data from digital attacks, theft, and damage." },
  ],
};

function findBestBank(subjectName: string): QuizQuestion[] {
  const name = subjectName.toLowerCase();
  if (QUESTION_BANK[subjectName]) return QUESTION_BANK[subjectName];
  for (const key of Object.keys(QUESTION_BANK)) {
    if (key === 'default') continue;
    if (name.includes(key.toLowerCase()) || key.toLowerCase().includes(name)) {
      return QUESTION_BANK[key];
    }
  }
  return QUESTION_BANK["default"];
}

export function getQuestionsForSubject(subjectName: string): QuizQuestion[] {
  return shuffle(findBestBank(subjectName)).slice(0, 10);
}

export function getQuestionCount(subjectName: string): number {
  return Math.min(findBestBank(subjectName).length, 10);
}

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
